name: Automate STOCK_LIST gh_bot

on:
  push:
  workflow_dispatch:
  schedule:
    # Asia/Kuala_Lumpur around 6pm, weekdays only
    - cron: "0 10 * * 1,2,3,4,5"

jobs:
  automation:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.3.0'

      - name: Run docker
        run: |
          docker build -t tsi .
          docker run -t --init --rm --cap-add=SYS_ADMIN \
            -v $PWD/contents/:/usr/src/app/contents \
            -v $PWD/stock-list.json/:/usr/src/app/stock-list.json \
            tsi

      - name: Commit changes
        uses: EndBug/add-and-commit@v5.1.0
        with:
          author_name: GitHub Actions Bot
          author_email: <>
          message: "[STOCK_LIST] gh_bot: Update with new changes"
          add: "stock-list.json contents"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
